### PR TITLE
Add ALL streaming api support

### PR DESCRIPTION
**Pull request by geoffrey-brier**
WIP

### CODE REVIEW

**Comment by geoffrey-brier** [comment]
Hey @egeloen , I think that I'm nearly finished on the implementation but there are _HEAVY_ problems:
- The following classes are dupplicated: Twitter, AbstractRequest (renamed to AbstractStreamingRequest), OptionInterface, AbstractOption, OptionFactory ...
- I need to pass a persistent callback somewhere (in the AbstractStreamingRequest constructor or in the call to `->createOAuthRequest()` so I need to update the widop/twitter-oauth library too.

I really think that we should rename widop/twitter-rest to widop/twitter and put both REST and streaming APIs here as passing a persistent callback good be a good feature for the REST API and it would reduce code dupplication as the API would work the same way!

**Comment by egeloen** [comment]
The issue here is the fact you have used the same approach for the rest & the stream API. My first idea about the stream API is to use the symfony event dispatcher in order to inform listener there is new datas which comes from twitter.

Can you explain how the user is informed when there are datas which are received?

Anyway, I will take a look at what you have done when I will find some times :)

**Comment by egeloen** [comment]
@geoffrey-brier After reading quickly the PR, IMO, the `Twitter` & `AbstractRequest` classes sounds like a duplication but in fact, they are not :) 

For the options, you're definitively right, it is pure duplication... What do you think about introducing a `widop/twitter-options` lib in order to share them?

**Comment by geoffrey-brier** [comment]
That could be cool indeed, but I think we should wait for this PR to be over before splitting the code. I'm having troubles implementing the resolvers, we'll need to discuss about it!

**Comment by egeloen** [comment]
@geoffrey-brier Does this PR is up to date with your last changes?

**Comment by egeloen** [comment]
@geoffrey-brier I know we have already discuss this part but it seems we don't have the same POV and no one would like to change his mind. 

To resume, for now, the big issue I have seen in this PR is the fact there is REST request in the Stream API (these requests are about stream management). I understand why you have made the choice to put them here (because it sounds like a stream feature) but IMO, it is not the case.

If we take a look at what each library should do, IMO, this one (stream) is a **technical** end point which allow to stream an HTTP request and then dispatch events in order to inform listeners there is something which happens in this stream. **It is its only purpose, nothing more**. Knowing that, a REST request can not be wrap in this lib as its purpose is totally different and would end up with lot of code duplication as you are trying to redo what the REST lib already does.

As an opposite, we have built a library which aims to send REST requests... so IMO, this one is totally appropriated in order to wrap this king of requests (whether or not it is about stream).

@tmartin I would like to have your POV about this one.

**Pull request closed without merging**
